### ISSUE TITLE
Getting stuck while creating keys

### ISSUE THREAD

**Issue by gsingh-ds** [antontutoveanu/crystals-kyber-javascript#8]
I was trying to test the following code:
```
import {K768_KeyGen, K768_Encrypt, K768_Decrypt} from 'crystals-kyber';
let pk_sk = K768_KeyGen();
```
it just got stuck at k768_KeyGen()
I dig around at found that "ntt" function is where it just stops.

Can you help?

**Comment by antontutoveanu** [comment]
Please provide details of your platform and running environment.

**Comment by gsingh-ds** [comment]
I have tried the upper code in multiple envs like docker containers. 
Steps to reproduce:
1. install node
2. npm install crystals-kyber
3. create index.js with upper code
4. add "type": "module" in package.json
5. node index.js

**Comment by gsingh-ds** [comment]
@antontutoveanu help?

**Comment by antontutoveanu** [comment]
I have been able to run the code using ```node kyber768.js``` for example.

I believe there is some npm issues which I plan on getting around. Apologies for delays.

**Comment by abmera** [comment]
I had the same issue, getting stuck at KeyGen, after some digging found that the culprit was this [line](https://github.com/antontutoveanu/crystals-kyber-javascript/blob/main/kyber768.js#L748):
`for (let j = start; j < start + l; j++)`.

For some reason in the source code from the npm package the `j` was declared twice: at the beginning of the `ntt` function and in the `for` loop  again. After removing the `let` in the for loop it worked. Github source code didn't have this issue though.

**Comment by abmera** [comment]
... same bug in `nttInverse` function where the `j` was declared twice (again only in npm's source code).

Also, `ArrayCompare` was missing in npm code which I just copied over from Github.

**Comment by antontutoveanu** [comment]
I have updated the code on both GitHub and NPM.

Please check again with the following usage:

```
// Import package
const kyber = require('crystals-kyber');

// To generate a public and private key pair (pk, sk)
let pk_sk = kyber.KeyGen768();
let pk = pk_sk[0];
let sk = pk_sk[1];

// To generate a random 256 bit symmetric key (ss) and its encapsulation (c)
let c_ss = kyber.Encrypt768(pk);
let c = c_ss[0];
let ss1 = c_ss[1];

// To decapsulate and obtain the same symmetric key
let ss2 = kyber.Decrypt768(c,sk);

// Test function with KATs
kyber.Test768();
```
